# Generated by Django 5.1.3 on 2025-12-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ名')),
                ('todos', models.ManyToManyField(related_name='tags', to='todo.todo', verbose_name='Todos')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
            },
        ),
    ]
